import{StyleSheet}from'react-native';

const styles = StyleSheet.create({
    container: {
      backgroundColor: "",
      height: '100%',
      width: '100%',
      marginTop: 10,
      padding: 10,
      fontFamily: 'SFProDisplay-Regular',
    },
    viewbox: {
      borderBottomColor: '#006CFF',
      borderBottomWidth: 0.2,
      marginBottom: 30,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: 0,
      padding: 20,
      height: 100,
    },
    TextStyle: {
      fontWeight: '500',
      letterSpacing: 0,
      fontSize: 30,
      color: 'black',
    },
    ADD: {
      fontSize: 30,
      fontWeight: '400',
      borderWidth: 3,
      color: '#006CFF',
      paddingHorizontal: 12,
      paddingVertical: 0,
      borderColor: '#006CFF',
      borderRadius: 50,
    },
    taskContainer: {
      padding: 15,
      paddingBottom: 18,
      display: 'flex',
      flexDirection: 'row',
      borderBottomWidth: 1, 
      borderBottomColor: '#a6a6a6',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    tick: {
      height: 30,
      width: 30,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: '#006CFF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    tickText: {
      fontSize: 20,
      color: '#F21368',
      textAlign: 'center',
    },
    texttodo: {
      fontSize: 20,
      letterSpacing: 1,
      color: 'black',
      fontWeight: '400',
    },
    dot: {
      height: 13,
      width: 13,
      borderRadius: 50,
      backgroundColor: 'red',
      marginLeft: 10,
    },
    AddTask: {
     
      borderWidth: 0.9,
      borderRadius: 20,
      padding: 20,
      borderColor: 'white',
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
    },
    Addtasktext: {
      fontSize: 30,
      fontWeight: '700',
      letterSpacing: 1,
      color: 'white',
    },
    Addtaskmsgbx: {
      height: 250,
      width: 350,
      borderColor: 'white',
      borderWidth: 0.9,
      borderRadius: 20,
    },
    Addtaskcd: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginHorizontal: 12,
    },
    AddtaskDone: {
      fontSize: 25,
      color: '#006CFF',
      fontWeight: '600',
      marginRight: 10,
    },
    AddtaskCreate: {
      fontSize: 25,
      fontWeight: '400',
      color: '#006CFF',
    },
    lastone: {
      marginTop: 10,
      textAlign: 'center',
      fontSize: 20,
      color: '#a6a6a6',
    },
  });

  export default styles;