const obj = [
  {
    id: 1,
    title: 'Pay for rent 💸',
    time: '8:00 AM',
    color: '#dadada',
    checked: false,
    editable: false,
    rightd: 0,
  },
  {
    id: 2,
    title: 'Buy a milk 🥛',
    time: '9:30 AM',
    color: '#61DEA4',
    checked: false,
    editable: false,
    rightd: 0,
  },
  {
    id: 3,
    title: 'Pickup Mickael 📍',
    time: '5:30 PM',
    color: '#F45E6D',
    checked: false,
    editable: false,
    rightd: 0,
  },
  {
    id: 4,
    title: 'Buy a chocolate 🍫',
    time: '6:00 PM',
    color: '#FFE761',
    checked: false,
    editable: false,
    rightd: 0,
  },
  {
    id: 5,
    title: 'OFFICE 📌',
    time: '10:00 AM',
    color: '#B678FF',
    checked: false,
    editable: false,
    rightd: 0,
  },
  // {
  //   id: 6,
  //   title: 'Music 🎶',
  //   time: '8:30 PM',
  //   color: '#dadada',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 7,
  //   title: 'Travel ✈️',
  //   time: '4:30 AM',
  //   color: '#61DEA4',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 8,
  //   title: 'Coding 📲',
  //   time: '12:00 PM',
  //   color: '#F45E6D',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 11,
  //   title: 'Meeting with Sarah 🗓️',
  //   time: '11:00 AM',
  //   color: '#FFE761',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 12,
  //   title: 'Grocery shopping 🛒',
  //   time: '3:00 PM',
  //   color: '#B678FF',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 13,
  //   title: 'Dentist appointment 🦷',
  //   time: '2:15 PM',
  //   color: '#dadada',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 14,
  //   title: 'Walk the dog 🐕',
  //   time: '7:30 AM',
  //   color: '#61DEA4',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 15,
  //   title: 'Call mom 📞',
  //   time: '6:00 PM',
  //   color: '#F45E6D',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 16,
  //   title: 'Finish report 📄',
  //   time: '1:45 PM',
  //   color: '#FFE761',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 17,
  //   title: 'Yoga 🧘‍♂️',
  //   time: '5:00 AM',
  //   color: '#B678FF',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 18,
  //   title: 'Dinner with friends 🍽️',
  //   time: '8:00 PM',
  //   color: '#dadada',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 19,
  //   title: 'Plan vacation 🌴',
  //   time: '4:00 PM',
  //   color: '#61DEA4',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
  // {
  //   id: 20,
  //   title: 'Watch a movie 🎬',
  //   time: '9:30 PM',
  //   color: '#B678FF',
  //   checked: false,
  //   editable: false,
  //   rightd: 0,
  // },
];

export default obj;
